new config option: device serial

diff --git a/blink1-weather b/blink1-weather
--- a/blink1-weather
+++ b/blink1-weather
@@ -5,16 +5,35 @@ region=Moscow,ru
 units=metric  # internal, metric, imperial
 sleep_time=22:00
 wake_up_time=06:40
-blink1_tool_args=
+device_serial=
 # END CONFIG
+
 
 prog=$(basename "$0")
 # http://openweathermap.org/forecast
 url="http://api.openweathermap.org/data/2.5/forecast/daily?q=${region}&mode=json&units=${units}&cnt=1"
 state_file=/tmp/blink1-weather.state
 
+
+device_id=
+
 blink1_tool() {
-    blink1-tool $blink1_tool_args "$@"
+    args=
+
+    if [ -n "$device_serial" ]; then
+        if [ -z "$device_id" ]; then
+            device_id=$(blink1-tool --list | sed -n "s/^id:\([0-9]\+\) - serialnum:${device_serial}\\b.*$/\1/p" | head -1)
+
+            if [ -z "$device_id" ]; then
+                echo "$prog: device not found" >&2
+                exit 1
+            fi
+        fi
+
+        args="$args --id $device_id"
+    fi
+
+    blink1-tool $args "$@"
     rc=$?
 
     if [ "$rc" != 0 ]; then
@@ -23,6 +42,7 @@ blink1_tool() {
         exit 1
     fi
 }
+
 
 if [ "$(date +%H%M)" -lt "$(echo "$wake_up_time" | tr -d :)" ]; then
     rm -f "$state_file"
@@ -36,12 +56,14 @@ if [ "$(date +%H%M)" -ge "$(echo "$sleep_time" | tr -d :)" ]; then
     exit 0
 fi
 
+
 weather_id=$(wget -q -O - "$url" | jq '.list[0].weather[0].id')
 
 if [ -z "$weather_id" ]; then
     echo "$prog: cannot get weather id" >&2
     exit 1
 fi
+
 
 state=0
 mode=off
@@ -94,6 +116,7 @@ case $weather_id in
     ;;
 esac
 
+
 if [ ! -e "$state_file" ]; then
     echo 0 >"$state_file"
     chmod 0666 "$state_file"
@@ -104,6 +127,7 @@ prev_state=$(cat "$state_file")
 if [ "$prev_state" != "$state" ]; then
     echo "$state" >"$state_file"
 fi
+
 
 case $mode in
   blink)
